---
slack_webhook_url: "{{ lookup('ansible.builtin.env', 'SLACK_WEBHOOK_URL') | default('', true) }}"
slack_channel_name: "{{ lookup('ansible.builtin.env', 'SLACK_CHANNEL') | default('', true) }}"
slack_username: "{{ lookup('ansible.builtin.env', 'SLACK_USERNAME') | default('AAP', true) }}"
slack_message_type: generic
slack_message: ""
slack_enabled: "{{ slack_webhook_url | length > 0 }}"
