---
- name: Place a change request in ServiceNow in Review
  servicenow.itsm.change_request:
    state: review
    number: "{{ request.record.number }}"
  delegate_to: localhost

- name: Close a change request
  servicenow.itsm.change_request:
    state: closed
    number: "{{ request.record.number }}"
    close_code: "{{ close_code }}"
    close_notes: "{{ close_notes }}"
  delegate_to: localhost

- name: Notify Slack about closed change request
  ansible.builtin.include_role:
    name: demo.process.slack
  vars:
    slack_message: >-
      ServiceNow change request {{ request.record.number }} has been closed with code {{ close_code }}.
